const { createClient } = require('@libsql/client');
require('dotenv').config({ path: '.env.local' });

const db = createClient({ 
  url: process.env.TURSO_DATABASE_URL, 
  authToken: process.env.TURSO_AUTH_TOKEN 
});

// 专业术语翻译字典 - 包装薄膜行业专用
const DICTIONARY = {
  // 基础材料
  '双向拉伸聚丙烯': 'Biaxially Oriented Polypropylene (BOPP)',
  '双向拉伸聚酯': 'Biaxially Oriented Polyester (BOPET)',
  '聚丙烯': 'Polypropylene (PP)',
  '聚酯': 'Polyester (PET)',
  '聚乙烯': 'Polyethylene (PE)',
  '聚氯乙烯': 'Polyvinyl Chloride (PVC)',
  '聚烯烃': 'Polyolefin (PO)',
  '尼龙': 'Nylon (PA)',
  '聚酰胺': 'Polyamide (PA)',
  '流延聚丙烯': 'Cast Polypropylene (CPP)',
  '流延': 'Cast',
  '镀铝': 'Metallized / Aluminum Coated',
  '镀铝膜': 'Metallized Film',
  '消光': 'Matte',
  '消光膜': 'Matte Film',
  '光膜': 'Plain Film / Glossy Film',
  '普通光膜': 'Plain Film',
  '热封': 'Heat Sealable',
  '热封型': 'Heat Sealable',
  '单面热封': 'Single-side Heat Sealable',
  '双面热封': 'Double-side Heat Sealable',
  '高阻隔': 'High Barrier',
  '阻隔': 'Barrier',
  '超薄': 'Ultra-thin',
  '电工级': 'Electrical Grade',
  '电容器': 'Capacitor',
  '电容膜': 'Capacitor Film',
  '电容镀铝膜': 'Metallized Capacitor Film',
  '镀铝聚酯薄膜': 'Metallized Polyester Film',
  
  // 应用领域
  '印刷复合包装': 'Printing and Lamination Packaging',
  '印刷复合': 'Printing and Lamination',
  '包装': 'Packaging',
  '食品包装': 'Food Packaging',
  '医药包装': 'Pharmaceutical Packaging',
  '医药': 'Pharmaceutical / Medical',
  '软包装': 'Flexible Packaging',
  '硬包装': 'Rigid Packaging',
  '卷烟包装': 'Cigarette Packaging',
  '烟包': 'Cigarette Pack',
  '香烟': 'Cigarette',
  '烟膜': 'Cigarette Film',
  '标签': 'Label',
  '标签膜': 'Label Film',
  '不干胶标签': 'Self-adhesive Label',
  '条码标签': 'Barcode Label',
  '胶带': 'Tape',
  '封箱胶带': 'Packing Tape / Carton Sealing Tape',
  '美纹纸胶带': 'Masking Tape',
  '双面胶带': 'Double-sided Tape',
  '胶水': 'Adhesive / Glue',
  '丙烯酸胶水': 'Acrylic Adhesive',
  '丙烯酸乳液': 'Acrylic Emulsion',
  '环保型': 'Eco-friendly / Environmentally Friendly',
  '涂布复合': 'Coating and Lamination',
  '涂布': 'Coating',
  '涂布膜': 'Coated Film',
  '功能性涂布': 'Functional Coating',
  '提升印刷适性': 'Improve Printability',
  '表面功能化处理': 'Surface Functional Treatment',
  'PVDC涂布': 'PVDC Coating',
  'K膜': 'K Film (PVDC Coated)',
  '丙烯酸涂布': 'Acrylic Coating',
  '丙烯酸涂布膜': 'Acrylic Coated Film',
  '收缩膜': 'Shrink Film',
  '热收缩': 'Heat Shrink',
  '环保型收缩膜': 'Eco-friendly Shrink Film',
  '透明度高': 'High Transparency',
  '拉伸缠绕膜': 'Stretch Wrap Film',
  '托盘包装防护': 'Pallet Packaging Protection',
  '缠绕膜': 'Stretch Film',
  '分切机': 'Slitting Machine',
  '高精度分切': 'High-precision Slitting',
  '薄膜分切设备': 'Film Slitting Equipment',
  '涂布机': 'Coating Machine',
  '高速涂布机': 'High-speed Coating Machine',
  '复合机': 'Laminating Machine',
  '收缩设备': 'Shrinking Equipment',
  '包装机械': 'Packaging Machinery',
  '自动化包装机械': 'Automated Packaging Machinery',
  '喷码设备': 'Coding Equipment / Inkjet Printer',
  '小字符喷码': 'Small Character Inkjet',
  '打码机': 'Coding Machine',
  '热转印碳带': 'Thermal Transfer Ribbon',
  '碳带': 'Ribbon',
  '蜡基': 'Wax-based',
  '混合基': 'Wax/Resin Mixed',
  '树脂基': 'Resin-based',
  '打印清晰': 'Clear Printing',
  '标签打印': 'Label Printing',
  '条码打印': 'Barcode Printing',
  '传真机': 'Fax Machine',
  '复印纸': 'Copy Paper',
  '双面复印纸': 'Double-sided Copy Paper',
  '80g': '80gsm',
  '防护口罩': 'Protective Face Mask',
  'KN95': 'KN95',
  '医疗防护': 'Medical Protection',
  '中间体': 'Intermediate',
  '精细化工中间体': 'Fine Chemical Intermediate',
  '伽马丁内酯': 'Gamma-Butyrolactone (GBL)',
  '纯度高': 'High Purity',
  '供应稳定': 'Stable Supply',
  '太阳能电池': 'Solar Cell',
  '光伏': 'Photovoltaic',
  'EVA胶膜': 'EVA Encapsulant Film',
  '背板材料': 'Backsheet Material',
  '双面双玻组件': 'Bifacial Double-glass Module',
  '清洁能源': 'Clean Energy',
  '高效': 'High Efficiency',
  '单晶': 'Monocrystalline',
  '双玻': 'Double-glass',
  
  // 规格参数
  '厚度': 'Thickness',
  '微米': 'µm / Micron',
  '重量': 'Weight',
  '克重': 'GSM / g/m²',
  '宽度': 'Width',
  '长度': 'Length',
  '颜色': 'Color',
  '透明': 'Transparent / Clear',
  '超透': 'Super Clear',
  '珠光': 'Pearlized',
  '珠光膜': 'Pearlized Film',
  '镭射': 'Holographic / Laser',
  '镭射膜': 'Holographic Film',
  '模压': 'Embossing',
  '防伪': 'Anti-counterfeit',
  '印刷': 'Printing',
  '凹版': 'Gravure',
  '柔版': 'Flexo',
  '数码印刷': 'Digital Printing',
  '油墨附着力': 'Ink Adhesion',
  '附着力强': 'Strong Adhesion',
  '抗静电': 'Anti-static',
  '抗穿刺': 'Puncture Resistant',
  '高强度': 'High Strength',
  '高张力': 'High Tensile Strength',
  '拉伸强度': 'Tensile Strength',
  '耐热': 'Heat Resistant',
  '耐冲击': 'Impact Resistant',
  '耐油': 'Oil Resistant',
  '阻隔性': 'Barrier Property',
  '保鲜': 'Freshness Preservation',
  '延长保鲜期': 'Extend Shelf Life',
  '食品级': 'Food Grade',
  'FDA标准': 'FDA Standard',
  'EU标准': 'EU Standard',
  '符合标准': 'Meets Standards',
  '认证': 'Certified / Certification',
  'ISO9001': 'ISO 9001',
  'ISO14001': 'ISO 14001',
  'SGS认证': 'SGS Certified',
  
  // 包装规格
  '大卷': 'Jumbo Roll',
  '小卷': 'Small Roll / Mini Roll',
  '分切': 'Slitting',
  '分切宽度': 'Slitting Width',
  '定制分切': 'Custom Slitting',
  '箱': 'Carton',
  '托盘': 'Pallet',
  '每箱': 'per Carton',
  '每托': 'per Pallet',
  '卷/箱': 'Rolls/Carton',
  '片/箱': 'Sheets/Carton',
  '包': 'Pack',
  '标准出口包装': 'Standard Export Packaging',
  '纸箱': 'Carton Box',
  '木箱': 'Wooden Case',
  '托盘包装': 'Pallet Packaging',
  '内包装': 'Inner Packaging',
  '外包装': 'Outer Packaging',
  '牛皮纸': 'Kraft Paper',
  '气泡膜': 'Bubble Film',
  '木板': 'Wooden Board',
  
  // 常用动词/形容词
  '适用于': 'Suitable for / Used for',
  '用于': 'Used for / For',
  '常用于': 'Commonly Used for',
  '广泛用于': 'Widely Used in',
  '包括': 'Including',
  '具有': 'Featuring / With',
  '特点': 'Features',
  '特性': 'Characteristics',
  '性能': 'Performance',
  '优异': 'Excellent / Outstanding',
  '优良': 'Good / Superior',
  '优秀': 'Excellent',
  '稳定': 'Stable',
  '稳定性': 'Stability',
  '均匀': 'Uniform',
  '均匀性': 'Uniformity',
  '表面': 'Surface',
  '光泽': 'Gloss / Glossy',
  '高光泽': 'High Gloss',
  '质感': 'Texture',
  '柔和': 'Soft',
  '平滑': 'Smooth',
  '平滑度': 'Smoothness',
  '垂直切面': 'Vertical Section',
  '卷绕': 'Winding',
  '紧实': 'Compact / Tight',
  '静电': 'Static Electricity',
  '低静电': 'Low Static',
  '厚度均匀性': 'Thickness Uniformity',
  '收缩': 'Shrinkage',
  '收缩稳定性': 'Shrinkage Stability',
  '热稳定性': 'Thermal Stability',
  '加工性': 'Processability',
  '机械性能': 'Mechanical Properties',
  '热特性': 'Thermal Properties',
  '涂层流程': 'Coating Process',
  '工程性': 'Engineering Performance',
  '基材': 'Base Film / Substrate',
  '基膜': 'Base Film',
  '复合': 'Lamination / Composite',
  '复合基材': 'Lamination Base',
  '多色印刷': 'Multi-color Printing',
  '印刷复合基材': 'Printing Lamination Base',
  '绝缘': 'Insulation',
  '电气绝缘': 'Electrical Insulation',
  '电工': 'Electrical',
  '电子': 'Electronic',
  'PCB标签': 'PCB Labels',
  '热转印': 'Thermal Transfer',
  '条码': 'Barcode',
  '标签打印': 'Label Printing',
  '颜色': 'Color',
  '红': 'Red',
  '粉': 'Pink',
  '绿': 'Green',
  '白': 'White',
  '紫': 'Purple',
  '蓝': 'Blue',
  '印刷客户': 'Printed Customer',
  '自有品牌': 'Private Label',
  'OEM': 'OEM',
  '定制': 'Custom / Customized',
  '客户要求': 'Customer Requirements',
  '根据客户要求': 'As per Customer Requirements',
  '可定制': 'Customizable',
  '规格': 'Specifications',
  '型号': 'Model',
  '产品型号': 'Product Model',
  
  // 更多专业术语 - 针对剩余未翻译内容
  '处理': 'Treatment / Treated',
  '表面处理': 'Surface Treatment',
  '质感柔和': 'Soft Texture',
  '高档包装': 'High-end Packaging',
  '单/双面': 'Single/Double-side',
  '自动包装生产线': 'Automatic Packaging Production Line',
  '食品': 'Food',
  '医药': 'Pharmaceutical',
  '超薄电工级聚酯薄膜': 'Ultra-thin Electrical Grade Polyester Film',
  '水性压敏胶带': 'Water-based Pressure-sensitive Adhesive Tape',
  '强粘耐久': 'Strong Adhesion & Durable',
  '通用封箱': 'General Carton Sealing',
  '环保型丙烯酸乳液': 'Eco-friendly Acrylic Emulsion',
  '适用于涂布复合': 'Suitable for Coating and Lamination',
  '高阻隔涂布膜': 'High Barrier Coated Film',
  '延长食品保鲜期': 'Extend Food Shelf Life',
  '表面功能化处理': 'Surface Functional Treatment',
  '提升印刷适性': 'Improve Printability',
  '流延聚丙烯薄膜': 'Cast Polypropylene Film',
  '热封性能优异': 'Excellent Heat Seal Performance',
  '高强度PA薄膜': 'High Strength PA Film',
  '耐穿刺': 'Puncture Resistant',
  '小字符喷码设备': 'Small Character Inkjet Equipment',
  '高精度薄膜分切设备': 'High-precision Film Slitting Equipment',
  '文名': 'Chinese Name',
  '又称': 'Also Known As',
  '简称': 'Abbreviation',
  '英文名': 'English Name',
  '英文别名': 'English Synonyms',
  '分子式': 'Molecular Formula',
  '相对分子量': 'Molecular Weight',
  '结构式': 'Structural Formula',
  'CAS号': 'CAS No.',
  'EINECS号': 'EINECS No.',
  '危险性类别': 'Hazard Class',
  '化学类别': 'Chemical Category',
  '熔点': 'Melting Point',
  '沸点': 'Boiling Point',
  '相对密度': 'Relative Density',
  '饱和蒸汽压': 'Saturated Vapor Pressure',
  '燃烧热': 'Heat of Combustion',
  '薄膜尺寸规格': 'Film Dimensional Specifications',
  '标称厚度': 'Nominal Thickness',
  '质量密度法厚度': 'Mass Density Method Thickness',
  '千分尺法厚度': 'Micrometer Method Thickness',
  '试验方法': 'Test Method',
  '润湿张力': 'Wetting Tension',
  '处理面': 'Treated Side',
  '摩擦系数': 'Coefficient of Friction',
  '静/动': 'Static/Dynamic',
  '热封强度': 'Heat Seal Strength',
  '光泽度': 'Gloss',
  '技术指标': 'Technical Specifications / Technical Parameters',
  '测试标准': 'Testing Standard',
  '典型数值': 'Typical Values',
  '企业标准': 'Enterprise Standard',
  '国家标准': 'National Standard',
  '国际标准': 'International Standard',
  '等级': 'Grade',
  '原料输送': 'Raw Material Feeding',
  '熔体挤出': 'Melt Extrusion',
  '机头膜管成型': 'Die Tube Formation',
  '膜管激冷定型': 'Tube Quenching',
  '第一膜泡': 'First Bubble',
  '膜管第一次牵引': 'First Tube Traction',
  '膜管除水': 'Tube Water Removal',
  '膜管第二次牵引': 'Second Tube Traction',
  '膜管预热': 'Tube Preheating',
  '加热': 'Heating',
  '膜管温度': 'Tube Temperature',
  '检测': 'Testing / Inspection',
  '膜管牵引拉伸吹胀': 'Tube Traction Stretching Blowing',
  '第二膜泡': 'Second Bubble',
  '第二膜泡冷却': 'Second Bubble Cooling',
  '制袋': 'Bag Making',
  '薄膜即': 'Film is',
  '也称': 'Also Called',
  '未拉伸': 'Unstretched',
  '按用途不同': 'Depending on Application',
  '可分为': 'Can be Divided into',
  '通用CPP': 'General CPP',
  '简称GCPP': 'Abbreviated as GCPP',
  '金属化': 'Metallized',
  '特性': 'Properties / Characteristics',
  '单位': 'Unit',
  '企业标准': 'Enterprise Standard',
  '国家标准': 'National Standard',
  'IC卡': 'IC Card',
  'ID卡': 'ID Card',
  '远距离': 'Long Distance',
  '主要技术参数': 'Main Technical Parameters',
  '适用涂膜树脂': 'Applicable Coating Resins',
  '涂复级': 'Coating Grade',
  '使用胶种': 'Adhesive Types Used',
  '基材': 'Base Film / Substrate',
  '基材BOPP': 'BOPP Base Film',
  '基料': 'Base Material',
  '全自动夹链贴膜制袋机': 'Fully Automatic Zipper Film Pasting Bag-making Machine',
  '特点': 'Features',
  '使用范围': 'Application Scope',
  '型号': 'Model',
  '电源电压': 'Power Supply Voltage',
  '功率': 'Power',
  '工作速度': 'Operating Speed',
  '印字面积': 'Printing Area',
  '单列': 'Single Row',
  '双列': 'Double Row',
  '三列': 'Triple Row',
  '热打印色带': 'Thermal Print Ribbon',
  '宽': 'Width',
  '高': 'Height',
  '化学名': 'Chemical Name',
  '十八烷酸': 'Stearic Acid',
  '十八酸': 'Octadecanoic Acid',
  '十八碳烷酸': 'Octadecanoic Acid',
  '司令': '',
  '三压法': 'Triple Pressed',
  '分子式': 'Molecular Formula',
  '档': 'End / Grade',
  '高档': 'High-end',
  '型': ' Type',
  '薄膜': ' Film',
  '设备': ' Equipment',
  '密度': ' Density',
  '千分尺': ' Micrometer',
  '压敏': ' Pressure-sensitive',
  '封箱': ' Carton Sealing',
  '延长': ' Extend',
  '保鲜期': ' Shelf Life',
  '生产线': ' Production Line',
  '自动': ' Automatic',
  '生产': ' Production',
  '制造': ' Manufacturing',
  '质量': ' Quality',
  '密度法': ' Density Method',
  '标称': ' Nominal',
  '尺寸': ' Dimensions',
  '规格': ' Specifications',
  '试验': ' Test',
  '方法': ' Method',
  '润湿': ' Wetting',
  '张力': ' Tension',
  '摩擦': ' Friction',
  '系数': ' Coefficient',
  '静': ' Static',
  '动': ' Dynamic',
  '热封': ' Heat Seal',
  '强度': ' Strength',
  '光泽': ' Gloss',
  '光泽度': ' Gloss',
  '技术': ' Technical',
  '指标': ' Indicators',
  '测试': ' Testing',
  '标准': ' Standard',
  '典型': ' Typical',
  '数值': ' Values',
  '企业': ' Enterprise',
  '国家': ' National',
  '国际': ' International',
  '等级': ' Grade',
  '原料': ' Raw Material',
  '输送': ' Feeding',
  '熔体': ' Melt',
  '挤出': ' Extrusion',
  '机头': ' Die Head',
  '膜管': ' Film Tube',
  '成型': ' Forming',
  '激冷': ' Quenching',
  '定型': ' Setting',
  '第一': ' First',
  '膜泡': ' Bubble',
  '牵引': ' Traction',
  '除水': ' Water Removal',
  '第二': ' Second',
  '预热': ' Preheating',
  '加热': ' Heating',
  '温度': ' Temperature',
  '检测': ' Testing',
  '拉伸': ' Stretching',
  '吹胀': ' Blowing',
  '冷却': ' Cooling',
  '制袋': ' Bag Making',
  '薄膜即': ' Film is',
  '也称': ' Also Called',
  '未拉伸': ' Unstretched',
  '按用途不同': ' Depending on Application',
  '可分为': ' Can be Divided into',
  '通用CPP': ' General CPP',
  '简称GCPP': ' Abbreviated as GCPP',
  '金属化': ' Metallized',
  '特性': ' Properties',
  '单位': ' Unit',
  '企业标准': ' Enterprise Standard',
  '国家标准': ' National Standard',
  'IC卡': 'IC Card',
  'ID卡': 'ID Card',
  '远距离': ' Long Distance',
  '主要技术参数': ' Main Technical Parameters',
  '适用涂膜树脂': ' Applicable Coating Resins',
  '涂复级': ' Coating Grade',
  '使用胶种': ' Adhesive Types Used',
  '基材': ' Base Film / Substrate',
  '基材BOPP': ' BOPP Base Film',
  '基料': ' Base Material',
  '全自动夹链贴膜制袋机': ' Fully Automatic Zipper Film Pasting Bag-making Machine',
  '特点': ' Features',
  '使用范围': ' Application Scope',
  '型号': ' Model',
  '电源电压': ' Power Supply Voltage',
  '功率': ' Power',
  '工作速度': ' Operating Speed',
  '印字面积': ' Printing Area',
  '单列': ' Single Row',
  '双列': ' Double Row',
  '三列': ' Triple Row',
  '热打印色带': ' Thermal Print Ribbon',
  '宽': ' Width',
  '高': ' Height',
  '化学名': ' Chemical Name',
  '十八烷酸': ' Stearic Acid',
  '十八酸': ' Octadecanoic Acid',
  '十八碳烷酸': ' Octadecanoic Acid',
  '司令': '',
  '三压法': ' Triple Pressed',
  '分子式': ' Molecular Formula',
  '嘉': 'Gamma',
  '丁内酯': 'Butyrolactone',
  '乙酸': 'Acetic Acid',
  '丙烯酸': 'Acrylic Acid',
  '正丁酯': 'n-Butyl Ester',
  '酯': 'Ester',
  '酸': 'Acid',
  '酯': 'Ester',
  '丁': 'Butyl',
  '丙': 'Prop',
  '烯': 'En',
  '酚': 'Phenol',
  '苯': 'Benzene',
  '甲': 'Methyl',
  '乙': 'Ethyl',
  '戊': 'Pentyl',
  '己': 'Hexyl',
  '庚': 'Heptyl',
  '辛': 'Octyl',
  '壬': 'Nonyl',
  '癸': 'Decyl',
  '十八': 'Octadec',
  '烷': 'Ane',
  '碳': 'Carbon',
  '氢': 'Hydrogen',
  '氧': 'Oxygen',
  '氮': 'Nitrogen',
  '硫': 'Sulfur',
  '磷': 'Phosphorus',
  '氯': 'Chlorine',
  '钠': 'Sodium',
  '钾': 'Potassium',
  '钙': 'Calcium',
  '镁': 'Magnesium',
  '铁': 'Iron',
  '铜': 'Copper',
  '锌': 'Zinc',
  '铝': 'Aluminum',
  '钛': 'Titanium',
  '铬': 'Chromium',
  '锰': 'Manganese',
  '镍': 'Nickel',
  '钴': 'Cobalt',
  '钼': 'Molybdenum',
  '钨': 'Tungsten',
  '钒': 'Vanadium',
  '铌': 'Niobium',
  '钽': 'Tantalum',
  '铼': 'Rhenium',
  '锇': 'Osmium',
  '铱': 'Iridium',
  '铂': 'Platinum',
  '金': 'Gold',
  '银': 'Silver',
  '汞': 'Mercury',
  '铅': 'Lead',
  '锡': 'Tin',
  '锑': 'Antimony',
  '铋': 'Bismuth',
  '钋': 'Polonium',
  '砹': 'Astatine',
  '氡': 'Radon',
  '钫': 'Francium',
  '镭': 'Radium',
  '锕': 'Actinium',
  '钍': 'Thorium',
  '镤': 'Protactinium',
  '铀': 'Uranium',
  '镎': 'Neptunium',
  '钚': 'Plutonium',
  '镅': 'Americium',
  '锎': 'Curium',
  '锫': 'Berkelium',
  '锩': 'Californium',
  '镄': 'Einsteinium',
  '钔': 'Fermium',
  '锘': 'Mendelevium',
  '铹': 'Nobelium',
  '律': 'Lawrencium',
  '鈹': 'Rutherfordium',
  '鈽': 'Dubnium',
  '鈾': 'Seaborgium',
  '鈿': 'Bohrium',
  '鉀': 'Hassium',
  '鉁': 'Meitnerium',
  '鉂': 'Darmstadtium',
  '鉃': 'Roentgenium',
  '鉄': 'Copernicium',
  '鉅': 'Nihonium',
  '鉆': 'Flerovium',
  '鉇': 'Moscovium',
  '鉈': 'Livermorium',
  '鉉': 'Tennessine',
  '鉊': 'Oganesson',

  // 句式连接词
  '，': ', ',
  '。': '. ',
  '；': '; ',
  '：': ': ',
  '、': ', ',
  '和': ' and ',
  '或': ' or ',
  '与': ' and ',
  '等': ' etc.',
  '等。': ' etc.',
  '等、': ' etc., ',
  '的': '',
  '是': 'is ',
  '为': 'is ',
  '可': 'can ',
  '能': 'able to ',
  '提供': 'provide ',
  '生产': 'produce / manufacture ',
  '制造': 'manufacture ',
  '供应': 'supply ',
  '出口': 'export ',
  '远销': 'export to ',
  '国家': 'countries',
  '地区': 'regions',
  '全球': 'worldwide / globally',
  '国内': 'domestic',
  '国际': 'international',
  '市场': 'market',
  '客户': 'customers / clients',
  '合作': 'cooperation / partnership',
  '合作伙伴': 'partners',
  '服务': 'service',
  '技术支持': 'technical support',
  '售后': 'after-sales',
  '质量': 'quality',
  '质量保证': 'quality guarantee',
  '质量管控': 'quality control',
  '严格检测': 'rigorous testing',
  '检测': 'testing / inspection',
  '检验': 'inspection',
  '认证': 'certification',
  '体系认证': 'system certification',
  '通过认证': 'certified',
  '获得认证': 'obtained certification',
};

// 简单的中文分词和翻译函数
function translateText(chineseText) {
  if (!chineseText || typeof chineseText !== 'string') return '';
  
  let text = chineseText.trim();
  
  // 按长度排序，优先匹配长词
  const sortedTerms = Object.entries(DICTIONARY).sort((a, b) => b[0].length - a[0].length);
  
  for (const [cn, en] of sortedTerms) {
    const regex = new RegExp(cn.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g');
    text = text.replace(regex, en);
  }
  
  // 清理多余空格和标点
  text = text
    .replace(/\s+/g, ' ')
    .replace(/,\s*,/g, ',')
    .replace(/\.\s*\./g, '.')
    .replace(/;\s*;/g, ';')
    .trim();
  
  // 首字母大写
  if (text) {
    text = text.charAt(0).toUpperCase() + text.slice(1);
  }
  
  return text;
}

// 更智能的翻译：先提取关键句，逐句翻译
function smartTranslate(chineseText) {
  if (!chineseText) return '';
  
  // 分句
  const sentences = chineseText.split(/[。；]/).filter(s => s.trim());
  const translated = sentences.map(s => translateText(s.trim())).filter(s => s);
  
  return translated.join('. ') + (translated.length > 0 ? '.' : '');
}

async function main() {
  console.log('Fetching English products with Chinese descriptions...');
  
  // 获取所有英文产品
  const products = await db.execute(`
    SELECT id, name, model, description, summary, intro 
    FROM products 
    WHERE lang='en' 
    AND (description GLOB '*[一-龥]*' OR intro GLOB '*[一-龥]*')
    ORDER BY id
  `);
  
  console.log(`Found ${products.rows.length} English products needing translation`);
  
  let updated = 0;
  let failed = 0;
  
  for (const p of products.rows) {
    try {
      const descZh = p.description || '';
      const introZh = p.intro || '';
      const summaryZh = p.summary || '';
      
      // 翻译 description (优先用 description，没有则用 intro，再没有用 summary)
      const descEn = smartTranslate(descZh) || smartTranslate(introZh) || smartTranslate(summaryZh) || '';
      const introEn = smartTranslate(introZh) || smartTranslate(descZh) || smartTranslate(summaryZh) || '';
      const summaryEn = smartTranslate(summaryZh) || smartTranslate(introZh) || smartTranslate(descZh) || '';
      
      // 更新数据库
      await db.execute({
        sql: `UPDATE products SET description=?, summary=?, intro=? WHERE id=?`,
        args: [descEn, summaryEn, introEn, p.id]
      });
      
      updated++;
      if (updated % 50 === 0) {
        console.log(`Progress: ${updated}/${products.rows.length} updated`);
      }
    } catch (err) {
      failed++;
      console.error(`Failed to update product ${p.id}:`, err.message);
    }
  }
  
  console.log(`\n=== Translation Complete ===`);
  console.log(`Updated: ${updated}`);
  console.log(`Failed: ${failed}`);
  
  // 验证结果
  const verify = await db.execute(`
    SELECT COUNT(*) as count FROM products 
    WHERE lang='en' AND (description GLOB '*[一-龥]*' OR intro GLOB '*[一-龥]*')
  `);
  console.log(`Remaining with Chinese chars: ${verify.rows[0].count}`);
  
  // 显示几个示例
  const samples = await db.execute(`
    SELECT id, name, substr(description, 1, 100) as desc_preview 
    FROM products 
    WHERE lang='en' 
    ORDER BY id LIMIT 10
  `);
  console.log('\nSample translations:');
  samples.rows.forEach(r => console.log(`  ID ${r.id}: ${r.name} - ${r.desc_preview}`));
  
  process.exit(0);
}

main().catch(e => { console.error(e); process.exit(1); });